PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <https://nickdrummond.github.io/star-wars-ontology/ontologies#>

SELECT
  (COUNT(DISTINCT ?corvusPropertiesAndUsage) AS ?corvusCount)
  (COUNT(DISTINCT ?calodanPropertiesAndUsage) AS ?calodanCount)
  (COUNT(DISTINCT ?combinedEvent) AS ?totalCount)
WHERE {
  {
    #first i find the total amount of properties related to Corvus
    ?corvusPropertiesAndUsage ?p1 ?o1 .
    FILTER (REGEX(STR(?o1), STR(:Corvus)))
  }

  {
    #i then get the total amount of properties related to Calodan
    ?calodanPropertiesAndUsage ?p2 ?o2 .
    FILTER (REGEX(STR(?o2), STR(:Calodan)))
  }

  # i combine both for total count
  {
    ?combinedPropertiesAndUsage ?p3 ?o3 .
    FILTER (
      REGEX(STR(?o3), STR(:Corvus)) ||
      REGEX(STR(?o3), STR(:Calodan))
    )
  }
}