# SPARQL not inferring all instances of Event, only instances of is direct subs

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sw: <http://null.com/star-wars#>
SELECT ?year ?event ?after ?during
WHERE {
	  ?event a sw:Event .
	  OPTIONAL { ?event sw:year ?year } .
	  OPTIONAL { ?event sw:after ?after }
	  OPTIONAL { ?event sw:during ?during }
	  }
ORDER BY ASC ( ?year )