# Birth, death and gender
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sw: <https://raw.githubusercontent.com/nickdrummond/star-wars-ontology/master/ontologies#>
SELECT ?person ?gender ?born ?died
WHERE {
	  ?person a sw:Living_thing .
	  OPTIONAL { ?person a ?restr .
				 ?restr rdf:type owl:Restriction ;
		  		  owl:onProperty sw:gender ;
				  owl:someValuesFrom ?gender}
	  OPTIONAL { ?person sw:born ?born }
	  OPTIONAL { ?event sw:deathOf ?person ;
	      sw:year ?died }
	  OPTIONAL { ?event sw:killingOf ?person ;
   	      sw:year ?died }
   	  }
ORDER BY ASC (?died)