# Planets and their features

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sw: <https://nickdrummond.github.io/star-wars-ontology/ontologies#>
SELECT (STRAFTER(STR(?within), "#") AS ?locatedIn2)
       (STRAFTER(STR(?in), "#") AS ?locatedIn1)
       (STRAFTER(STR(?p), "#") AS ?planet)
WHERE {
	  ?p a sw:Planet .
	  OPTIONAL {
		  ?p sw:locatedIn ?in
		  OPTIONAL { ?in sw:locatedIn ?within }
	  }
}
ORDER BY ASC (?locatedIn2)