# Planets and their features

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sw: <https://raw.githubusercontent.com/nickdrummond/starwarsontology/master/ontologies#>
SELECT ?planet ?sector ?region ?died
WHERE {
	  ?planet a sw:Planet .
	  OPTIONAL {
		  ?planet sw:location ?sector
		  OPTIONAL { ?sector sw:location ?region }
	  }
   	  }
ORDER BY ASC (?region)