PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sw: <https://nickdrummond.github.io/star-wars-ontology/ontologies#>
INSERT {
    ?newId a owl:NamedIndividual,
             ?filler .
    ?eventV sw:locatedIn ?newId .
}
WHERE {
	  ?eventV a sw:Event,
	            ?locRestr .
	  ?locRestr a owl:Restriction ;
	           owl:onProperty sw:locatedIn ;
	           owl:someValuesFrom ?filler .
	  bind(IRI(CONCAT(STR(?eventV), "_loc_", STR(RAND()))) as ?newId)
	  }
